#162949209 Add descriptive validation error messages
andela/ah-the-unsullied pull request #10
Opened 2019-01-11 15:13 UTC by Allan690

#### What does this PR do?
Adds descriptive error messages for the registration endpoint
#### Description of Task to be completed?
- Implement error messages for the registration endpoint
#### How should this be manually tested?
1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Make cloned directory the active directory: `cd ah-the-unsullied`
3. Checkout to the current branch: `git checkout ft-descriptive-validation-errors-162949211`
4. Set up a virtual environment and activate it.
```
- virtualenv <name_of_env>
- source <name_of_env>/bin/activate
```
5. Create a  .env file by doing `touch .env` in the current directory(root) and enter the database connection information in the format shown below: 
```
export DATABASE_URL=postgres://USERNAME:PASSWORD@HOST:5432/NAME
```
6. Create the database on terminal: `psql ah_unsullied`
7.  Export the environment variables: `source .env`
8. Make migrations: `python manage.py makemigrations && python manage.py migrate`
9. Create a super user: `python manage.py createsuperuser`
10. Run the server: `python manage.py runserver`
11. On Postman, navigate to [http://127.0.0.1/api/user/](http://127.0.0.1/api/user/) and enter the payload in this format:
```{
"user": 
         {
     "username": "your_username",
      "email": "your_email",
      "password": "your_password"
          }
}
```

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#162949211](https://www.pivotaltracker.com/story/show/162949211)
#### Screenshots (if appropriate)
(some of the use cases handled)
- When user does not enter their details
<img width="958" alt="screenshot 2019-01-10 at 21 21 23" src="https://user-images.githubusercontent.com/23090268/51041918-043b0800-15cc-11e9-8f84-002e9a7b7770.png">

- When user enters an existing username/email
<img width="1127" alt="screenshot 2019-01-11 at 18 10 31" src="https://user-images.githubusercontent.com/23090268/51041991-32b8e300-15cc-11e9-8e37-89ee3417541d.png">

- When the user enters invalid details
<img width="1125" alt="screenshot 2019-01-11 at 18 12 21" src="https://user-images.githubusercontent.com/23090268/51042076-73186100-15cc-11e9-8573-f5108c93d9df.png">

2019-01-14 06:14 UTC, MbugwaSami submitted a review, later dismissed

2019-01-14 07:06 UTC, kelvinwm submitted a review, later dismissed

2019-01-14 11:36 UTC, nesh-dev submitted a review, later dismissed

2019-01-14 11:42 UTC, MbugwaSami approved these changes

2019-01-14 11:43 UTC, MbugwaSami submitted a review, later dismissed

2019-01-14 11:43 UTC, nesh-dev submitted a review, later dismissed

2019-01-15 08:48 UTC, MbugwaSami reviewed
LGTM

2019-01-15 08:48 UTC, MbugwaSami submitted a review, later dismissed

2019-01-15 10:33 UTC, indungu requested changes
Please implement the requested changes. Also be sure to update the screenshots appropriately.

2019-01-15 10:33 UTC, indungu commented on authors/apps/authentication/serializers.py
> +        regex=r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\!\@#\$%\^&]).*',
A strict password policy is good but this appears to be a little too strict. Reduce the restriction to a require a number and a special character, that should be good enough.

2019-01-15 10:33 UTC, indungu commented on authors/apps/authentication/serializers.py
> +        'invalid': 'Password must contain at least 1 uppercase letter, '
On making the change requested on line 56, please adjust the validation message appropriately.

2019-01-15 10:33 UTC, indungu commented on authors/apps/authentication/serializers.py
> +            'invalid': 'Email entered is invalid. Please enter a valid email address'
Avoid repetition. `Please enter a valid email.` is descriptive enough.

2019-01-15 13:59 UTC, MbugwaSami approved these changes

2019-01-15 14:01 UTC, sylviawanjiku approved these changes

2019-01-15 14:03 UTC, indungu approved these changes

2019-01-15 14:09 UTC, merged