#162949216 User can create profile
andela/ah-the-unsullied pull request #12
Opened 2019-01-16 19:15 UTC by sylviawanjiku

#### What does this PR do?

Create a User Profile on registration

#### Description of Task to be completed?

* Write tests to for the creation of the user profile 
* Create a user profile that displays: username, bio, image/avatar

#### How should this be manually tested?

1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Cd into the cloned repo 
3. Git checkout to branch ft-user-profile-162949216
4. Set up a virtual environment and install requirements:
      ```
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt

     ```
5. Set up a .env file in the same level as the venv file and add the following:
      ```
            source venv/bin/activate
            export SECRET_KEY='yoursecretkey'
            export DATABASE_URL='postgres://yourdatabasename'
            export DJANGO_SETTINGS_MODULE='authors.settings'
            export CLOUDINARY_NAME=' '
            export CLOUDINARY_KEY=' '
            export CLOUDINARY_SECRET=' '

      ```
6. Then run: 
     ``` 
            source .env 
            ./manage.py migrate
            ./manage.py runserver
      ```

7. Fire up postman and test the following endpoints:

| EndPoint                                        | Functionality                           |
| -------------------------------- |:----------------------------:|
| POST   api/users/                          | Create user profile                 |
| GET     api/profiles/ username     | Get single user profile            |
| PUT     api/profiles/ username     | Edit single user profile           |
| GET     api/profiles/                       | Get all user profiles                | 

                                                    
use the following payload format to create a profile on registration:
```
{
  "user": {
    "email": "jake@jake.jake",
    "username": "jake",
    "password":"password"
  }
}
```

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[162949216](#162949216)
#### Screenshots (if appropriate)
None
#### Questions:

2019-01-17 07:23 UTC, nesh-dev requested changes

2019-01-17 07:23 UTC, nesh-dev commented on authors/apps/authentication/views.py
> +from rest_framework.views import APIView
This import is not used in the file.

2019-01-17 07:23 UTC, nesh-dev commented on authors/apps/profiles/views.py
> +from rest_framework.renderers import JSONRenderer
Import not used in file.

2019-01-17 07:23 UTC, nesh-dev commented on authors/apps/profiles/models.py
> +
PEP 8 two lines after the end of the class.

2019-01-17 08:06 UTC, nesh-dev submitted a review, later dismissed

2019-01-17 08:35 UTC, MbugwaSami requested changes
Please remove the blank line at the end of models.py and also add another blank line after line 36 on the same file.

2019-01-18 07:14 UTC, nesh-dev submitted a review, later dismissed

2019-01-18 07:16 UTC, Allan690 submitted a review, later dismissed

2019-01-21 05:49 UTC, nesh-dev submitted a review, later dismissed

2019-01-21 07:14 UTC, kwanj-k submitted a review, later dismissed

2019-01-21 07:16 UTC, MbugwaSami submitted a review, later dismissed

2019-01-21 10:47 UTC, indungu approved these changes
Nice work @sylviawanjiku and @kwanj-k

2019-01-21 10:47 UTC, kwanj-k approved these changes

2019-01-21 10:54 UTC, merged