#162949220 like dislike articles
andela/ah-the-unsullied pull request #18
Opened 2019-01-23 18:37 UTC by MbugwaSami

**What does this PR do?**
- Likes and Dislikes articles

**Description of the Task to be completed**
- Like and unlike an article
- Dislike and un-dislike an article
- Like to dislike and reverse to an article

**How should this be manually tested?**
- Clone the repository: git clone https://github.com/andela/ah-the-unsullied.git
- cd ah-the-unsullied
- git checkout ft-like-dislike-articles-162949220
- create .env on the ah-the-unsullied folder and add the following
```export DATABASE_URL='postgres://USER:PASSWORD@HOST:PORT/NAME'
     export SECRET_KEY="<your_secret_key_here>"
     export HOST_PASSWORD="<Gmail_Password>"
     export HOST_USER="<Gmail_Username>"
     export SMTP_HOST='smtp.gmail.com'
     export EMAIL_PORT='587
```
- Run the following commands 
```python3 -m venv venv
     source .env
     python manage.py migrate
     python manage.py runserver
```
- open postman and test the app
   
**Relevant PT story**
#162949220

**screenshots**
- N/A

2019-01-27 19:39 UTC, Allan690 commented
@MbugwaSami , I think you can change the title of the PR to make it more descriptive of the task. Something like, "Adds like and dislike features for articles" would be a better title, methinks.

2019-01-27 19:46 UTC, Allan690 commented on authors/tests/test_likes_dislikes.py
> +    def test_like(self):
Kindly add docstrings for your test cases. I think it will help other people understand your tests betteer.

2019-01-28 15:47 UTC, kwanj-k submitted a review, later dismissed

2019-01-28 18:43 UTC, nesh-dev submitted a review, later dismissed

2019-01-28 18:45 UTC, kwanj-k commented
Hey, you have two commits

2019-01-29 06:55 UTC, kwanj-k submitted a review, later dismissed

2019-01-29 06:58 UTC, nesh-dev submitted a review, later dismissed

2019-01-29 07:04 UTC, kelvinwm submitted a review, later dismissed

2019-01-29 07:38 UTC, sylviawanjiku approved these changes

2019-01-29 07:39 UTC, sylviawanjiku submitted a review, later dismissed

2019-01-29 07:43 UTC, kwanj-k submitted a review, later dismissed

2019-01-29 15:23 UTC, indungu requested changes

2019-01-29 15:23 UTC, indungu commented on authors/apps/articles/serializers.py
> +    def get_author(self, obj):
Please use a more descriptive parameter name `obj` is not descriptive enough.

2019-01-29 22:08 UTC, indungu approved these changes

2019-01-30 05:52 UTC, nesh-dev approved these changes

2019-01-30 06:03 UTC, kelvinwm approved these changes

2019-01-30 06:16 UTC, merged