#162949226 Add tags to articles
andela/ah-the-unsullied pull request #24
Opened 2019-01-28 19:11 UTC by kwanj-k

#### What does this PR do?

Enable articles to have tags

#### Description of Task to be completed?

* Have the following working

- [x] Add tags
- [x] Update tags
- [x] Remove tags

Use:
 * POST `api/articles` 
*  PUT `api/articles/<slug:slug>`

Payload:
```
{
  "article": {
    "title": "Your title",
    "description": "Ever wonder how?",
    "body":"body",
    "tagList": ["reactjs", "angularjs", "kwanj"]
  }
}
```
#### How should this be manually tested?

1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Cd into the cloned repo 
3. Git pull branch ft-article-tags-162949226
4. Set up a virtual environment and install requirements:
      ```
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt

     ```
5. Set up a .env file in the same level as the venv file and add the following:
      ```
           source venv/bin/activate
           export SECRET_KEY=""
           export DATABASE_URL=""
           export DJANGO_SETTINGS_MODULE='authors.settings'
           export CLOUDINARY_NAME=''
           export CLOUDINARY_KEY=''
           export CLOUDINARY_SECRET=''
           export HOST_PASSWORD=""
           export HOST_USER=""
           export SMTP_HOST=''
           export EMAIL_PORT=''
      ```
6. Then run: 
     ``` 
            source .env 
            ./manage.py migrate
            ./manage.py runserver
      ```
7. To test you need to register and login via postman.

* Register endpoint `/api/users`
* Login endpoint `/api/users/login`

#### Any background context you want to provide?
You need the above keys from the admin.
You need to verify account to add an article.

#### What are the relevant pivotal tracker stories?
[#162949226](https://www.pivotaltracker.com/story/show/162949226)
#### Screenshots (if appropriate)
Article tags:
<img width="1415" alt="screenshot 2019-01-28 at 22 05 22" src="https://user-images.githubusercontent.com/33450849/51859721-e8b05b00-2348-11e9-8d62-2b91e4043fb6.png">

#### Questions:

2019-01-31 11:47 UTC, nesh-dev submitted a review, later dismissed
Good work. LGTM.

2019-01-31 11:49 UTC, kelvinwm submitted a review, later dismissed

2019-01-31 11:54 UTC, MbugwaSami submitted a review, later dismissed

2019-01-31 14:43 UTC, Allan690 submitted a review, later dismissed

2019-01-31 17:18 UTC, indungu requested changes
Nice work @kwanj-k . Please make the following changes though.

2019-01-31 17:18 UTC, indungu commented on authors/apps/articles/models.py
> +# Create your models here.
Please remove this comment or make it more descriptive.

2019-01-31 17:18 UTC, indungu commented on authors/apps/articles/renderers.py
> +                    'ArticleCount': articles
The README has defined this key in `camelCase` not `TitleCase` please make this change.

2019-01-31 17:18 UTC, indungu commented on authors/apps/articles/renderers.py
> +                    'TagCount': tags
Why did you choose to add a `TagsCount` when only a list of tags is requested/required according to [this section of the README](https://github.com/andela/ah-the-unsullied#list-of-tags)?

2019-01-31 17:18 UTC, indungu commented on authors/apps/articles/urls.py
> +    path('/tags/', TagView.as_view())
Please remove the trailing slash in this path description to conform to the endpoint URL given in [this section of the README](https://github.com/andela/ah-the-unsullied#get-tags).

2019-01-31 17:18 UTC, indungu commented on authors/tests/test_ratings.py
> +        self.assertEqual(json.loads(response.content)['articles']['results'][0]['rating'],
Please correct this hanging indentation to meet PEP8 standards.

2019-01-31 17:18 UTC, indungu commented on authors/tests/test_tags.py
> +        self.client.get(self.get_verify_url(self.user_data))
Lines 15 to 17 are handled by the `verify_user` method in the TestBase class, please use that instead of repeating them.

2019-01-31 17:18 UTC, indungu commented on authors/tests/test_tags.py
> +        self.client.get(self.get_verify_url(self.user_data))
Lines 29 to 31 are handled by the `verify_user` method in the `TestBase` class, please use that instead of repeating them.

2019-01-31 17:48 UTC, Allan690 commented on authors/tests/test_auth_model.py
> +            username='Monster', email='drink@drink.com', password='hdfhfhhdf34W!')
The closing bracket would look much better in line 11 for readability cases.

2019-01-31 17:49 UTC, Allan690 commented on authors/tests/test_auth_model.py
> +            username='Monster', email='drink@drink.com', password='hdfhfhhdf34W!')
Same here

2019-02-01 05:58 UTC, nesh-dev submitted a review, later dismissed

2019-02-01 06:11 UTC, kelvinwm submitted a review, later dismissed

2019-02-01 07:09 UTC, indungu approved these changes

2019-02-01 07:21 UTC, Allan690 approved these changes

2019-02-01 07:21 UTC, nesh-dev approved these changes

2019-02-01 07:25 UTC, merged