feat(shares): implement share articles via email and social platforms
andela/ah-the-unsullied pull request #26
Opened 2019-01-29 18:53 UTC by sylviawanjiku

#### What does this PR do?

Create comments for an article
#### Description of Task to be completed?

- add share article via email
- add share article facebook and twitter
- add tests on share articles

#### How should this be manually tested?

1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Cd into the cloned repo 
3. Git checkout to branch ft-configure-jwt-162949210
4. Set up a virtual environment and install requirements:
      ```
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt

     ```
5. Set up a .env file in the same level as the venv file and add the following:
      ```
            source venv/bin/activate
            export SECRET_KEY='yoursecretkey'
             export DATABASE_URL='postgres://yourdatabasename'

      ```
6. Then run: 
     ``` 
            source .env 
            ./manage.py migrate
            ./manage.py runserver
      ```

7. Fire up postman and test the following endpoints:

| EndPoint                       | Functionality                           |
| ---------------------- |:----------------------------:|
| POST     api/articles/ `<slug>`/comments  | Create Comment                       |
| POST     api/articles/`<slug>`/comments/<int:id>                     |Create Child Comment |
| GET     api/articles/`<slug>`/comments   |Retrieve Comment                       |
| GET     api/articles/`<slug>`/comments/<int:id>                   |Retrieve thread for Comment |

                                                    
use the following payload format:
```
{
    "body": "This is a parent comment"
  }
```
```
{
"comment": {
    "body": "This is a child comment"
  }
}
```

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[162949219](https://www.pivotaltracker.com/story/show/162949219)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/28457081/51674316-5b37d880-1fe1-11e9-96af-bad5aaa65714.png)
![image](https://user-images.githubusercontent.com/28457081/51674327-63901380-1fe1-11e9-8947-2ed09f0f1f26.png)

#### Questions:

2019-01-31 11:56 UTC, kwanj-k commented on authors/apps/articles/templates/share_article.html
> +      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
Line too long, probably do a line now and then when the line is too long

2019-01-31 15:53 UTC, kwanj-k reviewed
Please update your PR description, it's directing me to a different branch

2019-02-01 08:19 UTC, indungu requested changes
Please make the following changes.
 
And update the PR description as @kwanj-k requested while you are at it too please.
```markdown
[#162949230](https://www.pivotaltracker.com/story/show/162949230)
```

2019-02-01 08:19 UTC, indungu commented on authors/apps/articles/views/articles.py
> +    EmailCheckSerializer
Move this to line 18 please

2019-02-04 18:38 UTC, indungu submitted a review, later dismissed

2019-02-04 18:39 UTC, kwanj-k commented on authors/apps/articles/migrations/0002_auto_20190130_1803.py
> +    ]
Add a new line here

2019-02-04 18:39 UTC, kwanj-k commented on authors/apps/articles/migrations/0003_rating.py
> +    ]
Add a new line here

2019-02-04 18:40 UTC, kwanj-k commented on authors/apps/articles/templates/share_article.html
> +      url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
Line too long

2019-02-04 18:41 UTC, kwanj-k commented on authors/apps/articles/templates/share_article.html
> +      url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');
Line too long, please consider making it shorter

2019-02-04 18:46 UTC, kwanj-k commented on authors/tests/base_test.py
> +import os
I read somewhere such an import should at the top of the file, ie os imports come first, the third party then local imports
And you have put it under the comment 'local imports', kindly look in to that

2019-02-04 19:18 UTC, Allan690 commented on authors/apps/articles/serializers.py
> +class EmailCheckSerializer(serializers.Serializer):
This serializer already exists in authentications/serializers.py. I think you can just call the one in the authentications app if you need it in your views. That will help us keep our code DRY

2019-02-05 09:09 UTC, kwanj-k approved these changes

2019-02-05 09:10 UTC, nesh-dev approved these changes

2019-02-05 09:14 UTC, merged