#162949204 Configure backend to use a Postgres database
andela/ah-the-unsullied pull request #3
Opened 2019-01-08 14:11 UTC by Allan690

#### What does this PR do?
Configures the backend of the application to use Postgres as it's database
#### Description of Task to be completed?
- Integrate a Postgres database and make the migrations
- add .env file with local db configurations
- Change database settings in the settings.py file
#### How should this be manually tested?
1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Make cloned directory the active directory: `cd ah-the-unsullied`
3. Checkout to the current branch: `git checkout ch-configure-postgres-db-162949204`
4. Set up a virtual environment and activate it.
```
- virtualenv <name_of_env>
- source <name_of_env>/bin/activate
```
5. Create a  .env file by doing `touch .env` and enter the database connection information as shown below: 
```
export DB_NAME='ah_unsullied'
export DB_USER='<your_db_username_here'
export DB_PASSWORD='<password>'
export PORT='<db_port>'  //default is 5432
export HOST='localhost'
```
6. Create the database on terminal: `psql ah_unsullied`
7.  Export the environment variables: `source .env`
8. Make migrations: `python manage.py makemigrations && python manage.py migrate`
9. Create a super user: `python manage.py createsuperuser`
10. Run the server: `python manage.py runserver`
11. Login with the credentials of the super user by navigating to: `localhost:8000/admins`
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#162949204](https://www.pivotaltracker.com/story/show/162949204)

2019-01-08 14:21 UTC, kwanj-k requested changes
Good work Allan
But I have a few concerns
since am also setting up the database in production/staging, it would be wise if we use dj-database-url
[more info here](https://github.com/kennethreitz/dj-database-url) so we can both use the same settings file.
With dj-database-url you will just pass a database URL variable

2019-01-08 14:25 UTC, Allan690 commented
Thanks, @kwanj-k.  Let me work on making those changes. I think it will be easier that way

2019-01-08 14:28 UTC, MbugwaSami commented
Good work Allan

2019-01-08 14:28 UTC, kelvinwm commented
5. Create a .env file by doing touch .env and enter the database connection information as shown below: - Where do we create the.env file?

2019-01-08 14:29 UTC, Allan690 commented
> 1. Create a .env file by doing touch .env and enter the database connection information as shown below: - Where do we create the.env file?

I just updated the description to show that the file is created in the root directory. Please check

2019-01-08 15:15 UTC, kwanj-k submitted a review, later dismissed

2019-01-08 15:22 UTC, nesh-dev submitted a review, later dismissed

2019-01-08 15:25 UTC, sylviawanjiku submitted a review, later dismissed

2019-01-09 06:14 UTC, kelvinwm submitted a review, later dismissed

2019-01-09 07:17 UTC, MbugwaSami submitted a review, later dismissed

2019-01-09 07:27 UTC, sylviawanjiku commented
Update your documentation of the PR.

2019-01-09 07:29 UTC, Allan690 commented
> Update your documentation of the PR.

Just did so, Please check

2019-01-09 11:39 UTC, indungu requested changes
Please remove all this lint related file changes. The only files required for this PR are the `authors/settings.py` and the `requirements.txt` file

2019-01-09 11:39 UTC, indungu commented on authors/apps/authentication/models.py
> -    Django to create a `User` for free.
Remove from changed files.

2019-01-09 11:39 UTC, indungu commented on authors/apps/authentication/serializers.py
> -    # Passwords must be at least 8 characters, but no more than 128
Remove from changed files

2019-01-09 11:39 UTC, indungu commented on authors/apps/authentication/views.py
> -
Remove from changed files.

2019-01-09 11:39 UTC, indungu commented on authors/urls.py
> -
Remove from changed files.

2019-01-09 12:32 UTC, Allan690 commented
Closing this PR due to unresolvable conflicts

2019-01-09 12:32 UTC, closed without merging