#162949234 Track edit history of comments
andela/ah-the-unsullied pull request #30
Opened 2019-01-30 16:36 UTC by MbugwaSami

**What does this PR do?**
- Tracks edit history of comments

**Description of the Task to be completed**
- Track edit history of comments
- Display current and previous comments

**How should this be manually tested?**
- Clone the repository: git clone https://github.com/andela/ah-the-unsullied.git
- cd ah-the-unsullied
- git checkout ft-track-comment-history-162949234
- create .env on the ah-the-unsullied folder and add the following
```export DATABASE_URL='postgres://USER:PASSWORD@HOST:PORT/NAME'
     export SECRET_KEY="<your_secret_key_here>"
     export HOST_PASSWORD="<Gmail_Password>"
     export HOST_USER="<Gmail_Username>"
     export SMTP_HOST='smtp.gmail.com'
     export EMAIL_PORT='587
```
- Run the following commands 
```python3 -m venv venv
     source .env
     python manage.py migrate
     python manage.py runserver
```
- open postman and test the app
   
**Relevant PT story**
#162949220

**screenshots**
- N/A

2019-01-31 12:42 UTC, kwanj-k requested changes
Kindly avoid pip freezing, add the dependencies you added to requirements.txt only

2019-01-31 12:43 UTC, sylviawanjiku commented
According to the engineering playbook you should use small letters in your commit message

2019-01-31 12:44 UTC, sylviawanjiku reviewed
According to the engineering playbook you should use small letters in your commit message

2019-01-31 12:45 UTC, sylviawanjiku requested changes
According to the engineering playbook you should use small letters in your commit message

2019-02-04 07:12 UTC, kwanj-k submitted a review, later dismissed

2019-02-04 07:21 UTC, sylviawanjiku submitted a review, later dismissed

2019-02-04 08:20 UTC, indungu requested changes
Nice work. Please make the requested change.

2019-02-04 08:20 UTC, indungu commented on authors/tests/base_test.py
> +        id = response.data['id']
`id` is a reserved keyword in python, please change this variable name to `comment_id`.

2019-02-04 11:50 UTC, kwanj-k submitted a review, later dismissed

2019-02-04 12:11 UTC, kelvinwm approved these changes

2019-02-04 14:51 UTC, indungu approved these changes

2019-02-04 15:19 UTC, merged