#162949206 Setup and deploy base application to Heroku
andela/ah-the-unsullied pull request #4
Opened 2019-01-09 06:50 UTC by kwanj-k

#### What does this PR do?

Setup and deploy application to Heroku

#### Description of Task to be completed?

* Deploy base to production on Heroku
* Set up Postgres on Heroku
* Configure the staging pipeline
* Update settings and other deployments settings
* Update doc string links to point to Django 2.1 documentation

#### How should this be manually tested?

1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Cd into the cloned repo 
3. Git pull branch ch-deploy-to-heroku-162949206
4. Set up a virtual environment and install requirements:
      ```
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt

     ```
5. Set up a .env file in the same level as the venv file and add the following:
      ```
            source venv/bin/activate
            export SECRET_KEY='yoursecretkey'
             export DATABASE_URL='postgres://yourdatabasename'

      ```
6. Then run: 
     ``` 
            source .env 
            ./manage.py migrate
            ./manage.py runserver
      ```
7. To test locally, create a superuser and visit the route provided by the server to test admin site:
      ```
             ./manage.py createsuperuser - to createsuperuser

      ```
8. To test the Live version visit:
  * [Base](https://ah-the-unsullied.herokuapp.com/admin/)
  * [Staging](ah-the-unsullied-staging.herokuapp.com/admin/)

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[162949206](#162949206)
#### Screenshots (if appropriate)
None
#### Questions:

2019-01-09 07:24 UTC, MbugwaSami reviewed
Good work kwanj

2019-01-09 07:24 UTC, MbugwaSami submitted a review, later dismissed

2019-01-09 12:49 UTC, indungu requested changes

2019-01-09 12:49 UTC, indungu commented on .gitignore
> +
A single blank line is enough, please remove extra whitespace.

2019-01-09 19:52 UTC, MbugwaSami reviewed
LGTM

2019-01-09 19:54 UTC, MbugwaSami submitted a review, later dismissed

2019-01-10 09:38 UTC, Allan690 requested changes
Good work, but kindly shorten the title of your commit message
<img width="633" alt="screenshot 2019-01-10 at 12 37 37" src="https://user-images.githubusercontent.com/23090268/50959664-85af6f00-14d4-11e9-9fb3-3502ccd10dfe.png">

2019-01-10 09:47 UTC, Allan690 submitted a review, later dismissed

2019-01-10 09:58 UTC, indungu requested changes
Hey @kwanj-k , nice work... I still have an issue with your commit message header though.
The scope of the task can be better titled as just `deployment` rather than `Deploy and setup pipelines`, yes?
Also, please adhere strictly to the [commit message conventions](https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#commit-message) I shared, the [commit message header]() should ideally be in small caps.

2019-01-10 10:10 UTC, indungu approved these changes

2019-01-10 10:11 UTC, nesh-dev approved these changes

2019-01-10 10:11 UTC, Allan690 approved these changes
I think it looks better now that you implemented the feedback

2019-01-10 10:12 UTC, merged