feat(documentation)Document the API using Swagger
andela/ah-the-unsullied pull request #7
Opened 2019-01-10 09:45 UTC by nesh-dev

- Add django-rest-swagger
  - Add swagger configs
  - Document the existing API endpoints

[Starts #162949209]

2019-01-10 14:27 UTC, kwanj-k submitted a review, later dismissed

2019-01-10 14:28 UTC, sylviawanjiku submitted a review, later dismissed

2019-01-10 18:45 UTC, Allan690 requested changes
Please include a colon before the word "Document" keeping in line with the format outlined[ here](https://github.com/andela/getmyshop/wiki/Commit-Message-Convention#format-of-the-commit-message) 

<img width="633" alt="screenshot 2019-01-10 at 21 41 47" src="https://user-images.githubusercontent.com/23090268/50989468-8a017980-1520-11e9-9da3-619c220f6240.png">

2019-01-11 06:11 UTC, kwanj-k approved these changes

2019-01-11 06:12 UTC, kwanj-k requested changes
Make sure the commit message uses lower case only

2019-01-11 06:43 UTC, Allan690 submitted a review, later dismissed

2019-01-11 07:14 UTC, Allan690 submitted a review, later dismissed
LGTM

2019-01-11 07:30 UTC, MbugwaSami submitted a review, later dismissed

2019-01-11 07:40 UTC, kwanj-k submitted a review, later dismissed

2019-01-11 09:21 UTC, kelvinwm submitted a review, later dismissed

2019-01-14 19:40 UTC, indungu requested changes
The [review app](https://ah-the-unsullied-staging-pr-7.herokuapp.com/) is currently down. This makes it hard to approve this changes since merging them might bring down staging. Please address this ASAP.

2019-01-15 07:00 UTC, kwanj-k commented
The review app is now up. 👍

2019-01-15 07:00 UTC, kwanj-k submitted a review, later dismissed

2019-01-15 07:01 UTC, MbugwaSami submitted a review, later dismissed

2019-01-15 07:01 UTC, Allan690 submitted a review, later dismissed

2019-01-15 09:15 UTC, indungu requested changes
Please address all the highlighted issues. The endpoints are also not working as expected.
![image](https://user-images.githubusercontent.com/30072633/51170339-48c1ee80-18bf-11e9-9f3e-f0a6e7e701c4.png)

2019-01-15 09:15 UTC, indungu commented on authors/apps/authentication/views.py
> +from rest_framework import generics
This import could me more specific, please switch it to one with just the Classes you intend to use.

`from rest_framework.generic import CreateAPIView, RetrieveUpdateAPIView`

2019-01-15 09:15 UTC, indungu commented on requirements.txt
> +django-rest-swagger==2.1.0
There is a newer version of this dependency, please use version `2.2.0`.

2019-01-15 09:15 UTC, indungu commented on authors/settings.py
> +    # 'DEFAULT_AUTHENTICATION_CLASSES': (
Remove all commented out code.

2019-01-15 09:25 UTC, nesh-dev commented on authors/apps/authentication/views.py
> +from rest_framework import generics
The custom JSON renderer has changed the format of the data. It should be passed as included in the README file.

2019-01-15 09:47 UTC, nesh-dev commented on requirements.txt
> +django-rest-swagger==2.1.0
Version 2.2 has issues with input fields, There was a recommendation to donwgrade.

2019-01-15 12:56 UTC, Allan690 submitted a review, later dismissed

2019-01-16 13:09 UTC, kwanj-k submitted a review, later dismissed

2019-01-16 13:19 UTC, Allan690 approved these changes

2019-01-16 13:20 UTC, sylviawanjiku approved these changes

2019-01-16 13:21 UTC, indungu approved these changes

2019-01-16 13:22 UTC, merged