#162949210 Setup jwt authentication
andela/ah-the-unsullied pull request #8
Opened 2019-01-11 07:24 UTC by kwanj-k

#### What does this PR do?

Configure jwt authentication and tests for the same

#### Description of Task to be completed?

* Write tests to check if the token is returned on login/registration
* Create a token on registration/signup

#### How should this be manually tested?

1. Clone the repo: `git clone https://github.com/andela/ah-the-unsullied.git`
2. Cd into the cloned repo 
3. Git checkout to branch ft-configure-jwt-162949210
4. Set up a virtual environment and install requirements:
      ```
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt

     ```
5. Set up a .env file in the same level as the venv file and add the following:
      ```
            source venv/bin/activate
            export SECRET_KEY='yoursecretkey'
             export DATABASE_URL='postgres://yourdatabasename'

      ```
6. Then run: 
     ``` 
            source .env 
            ./manage.py migrate
            ./manage.py runserver
      ```

7. Fire up postman and test the following endpoints:

| EndPoint                       | Functionality                           |
| ---------------------- |:----------------------------:|
| POST     api/users/      | Register User                          |
| POST     api/users/login/ | Login a user                        |

                                                    
use the following payload format:
```
{
  "user": {
    "email": "jake@jake.jake",
    "username": "jake",
    "password":"password"
  }
}
```

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[162949210](#162949210)
#### Screenshots (if appropriate)
None
#### Questions:

2019-01-14 06:04 UTC, Allan690 submitted a review, later dismissed

2019-01-14 06:05 UTC, MbugwaSami submitted a review, later dismissed

2019-01-14 06:19 UTC, kelvinwm submitted a review, later dismissed

2019-01-14 06:28 UTC, nesh-dev requested changes

2019-01-14 06:28 UTC, nesh-dev commented on authors/apps/authentication/backends.py
> +#By default, django-restframework--jwt generates a token
To follow PEP8 standards there should be space between the # and the start of the comment.
There should also be space between the comment and the function.

2019-01-14 06:28 UTC, nesh-dev commented on authors/apps/authentication/serializers.py
> +        #print(validated_data)
kindly remove the commented lines.

2019-01-14 06:42 UTC, nesh-dev submitted a review, later dismissed

2019-01-14 06:45 UTC, sylviawanjiku submitted a review, later dismissed

2019-01-14 07:32 UTC, nesh-dev submitted a review, later dismissed

2019-01-14 07:33 UTC, sylviawanjiku submitted a review, later dismissed

2019-01-14 14:33 UTC, indungu requested changes

2019-01-14 14:33 UTC, indungu commented on authors/apps/authentication/backends.py
> +#with user data of our choosing
Please use the PEP8 multiline comment style guides.

2019-01-14 14:33 UTC, indungu commented on authors/apps/authentication/backends.py
> +
Please remove unnecessary whitespace characters.

2019-01-14 15:57 UTC, sylviawanjiku submitted a review, later dismissed

2019-01-14 15:57 UTC, nesh-dev submitted a review, later dismissed

2019-01-14 15:58 UTC, Allan690 submitted a review, later dismissed

2019-01-15 06:33 UTC, sylviawanjiku approved these changes

2019-01-15 07:11 UTC, nesh-dev approved these changes

2019-01-15 09:32 UTC, MbugwaSami approved these changes

2019-01-15 09:33 UTC, indungu approved these changes

2019-01-15 09:33 UTC, merged